name: Lint and Test Charts

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.0

      - name: Debug - Print Branch Information
        run: |
          echo "Current branch: ${{ github.ref }}"
          echo "Target branch: ${{ github.event.repository.default_branch }}"

      # Lint charts (does not require a Kubernetes cluster)
      - name: Run chart-testing (lint)
        run: |
          echo "Running ct lint..."
          ct lint  --config ct.yaml --debug 

      # Create Kind cluster for installation testing
      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: chart-testing
          wait: 60s

      # Test chart installation (requires Kubernetes cluster)
      - name: Run chart-testing (install)
        run: |
          echo "Running ct install..."
          ct install  --config ct.yaml --debug 
