name: Lint and Test Charts

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.0

      # Debugging Step: Print out the current branch and the default branch
      - name: Debug - Print Branch Information
        run: |
          echo "Current branch: ${{ github.ref }}"
          echo "Target branch: ${{ github.event.repository.default_branch }}"

      # Run chart-testing (list-changed) and output debug info
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          echo "Changed charts: $changed"
          if [[ -n "$changed" ]]; then
            echo "Setting changed=true"
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changed charts detected"
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      # Debugging Step: Check what the output of list-changed is
      - name: Debug - Check list-changed output
        run: |
          echo "list-changed output: ${{ steps.list-changed.outputs.changed }}"

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          echo "Running ct lint..."
          ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.10.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          echo "Running ct install..."
          ct install --target-branch ${{ github.event.repository.default_branch }}
